### ISSUE TITLE
Missing .xml to install/update

### ISSUE THREAD

**Issue by itsAliAvali** [ABSAhmad/IpsCoinpaymentsGateway#1]
I have purchased and cannot update without the .xml  ; (xml missing on github repo)

**Comment by itsAliAvali** [comment]
not as simple as grabbing all files and just making a .tar like you would for an application.

**Comment by ABSAhmad** [comment]
Then get it from the IPS Marketplace.

**Comment by itsAliAvali** [comment]
It's not letting me download because it's asking for renewal. You've made
this open source, just got to properly distribute (even if you don't do
technical support for GitHub releases)

**Comment by itsAliAvali** [comment]
@ABSAhmad "I will only provide support to those, who purchased the gateway however." I have, now you are violating your own contract to your clients. you already have it updated here to match IPS MP, but youre just missing the coinpayments.xml file to update the plugin.

**Comment by ABSAhmad** [comment]
> you are violating your own contract

Please clarify, I stated that the code is open-source which it is.

I only have to support clients with an *active* license, I do not need to distribute the code on github, the xml or whatever - I do that because I *want* to.
